version: '3'

services:
  auth-generator:
    image: andrianovartemii/gm-test-task-auth-generator:latest
    ports:
      - "8082"
    environment:
      AUTH_TOKEN_LIFETIME: 2

  gateway:
    build:
      context: .
    restart: always
    ports:
      - "8080"
    env_file:
      - .env
