tokenGen:
  port : "8082"
  host: "localhost"
  timeout: 10000000000 #10s
  retry: 10
  timeoutRetry:  300000000 #3s

srv: 
  maxHeaderBytes: 1048576  
  readTimeout: 10000000000   #seconds * time 
  writeTimeout: 10000000000  
  readHeaderTimeout: 10000000000
  timeOutSec: 10 # 10s     
  port: "8080"          
  host: "localhost"

rabbit:
  host: "localhost"
  port: "5672"
  username: "guest"
  password: "guest"
